<?php
/**
 * InlineResponse2001DataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PreflightAPI
 *
 * Preflighting in printing is the process of checking a design file for inefficiencies/errors and making sure it’s set-up correctly before before sending it to print or final production. Preparation for printed jobs ranges according to the complexity of a project, but there are some fundamental things to check before send each print job to ensure that you are producing the intended outcome.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2001DataTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2001Data
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2001DataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2001Data"
     */
    public function testInlineResponse2001Data()
    {
    }

    /**
     * Test attribute "framed_pdf"
     */
    public function testPropertyFramedPdf()
    {
    }

    /**
     * Test attribute "fixed_pdf"
     */
    public function testPropertyFixedPdf()
    {
    }

    /**
     * Test attribute "preview"
     */
    public function testPropertyPreview()
    {
    }

    /**
     * Test attribute "file_size"
     */
    public function testPropertyFileSize()
    {
    }

    /**
     * Test attribute "preflight_effect"
     */
    public function testPropertyPreflightEffect()
    {
    }

    /**
     * Test attribute "preflight_status"
     */
    public function testPropertyPreflightStatus()
    {
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
    }

    /**
     * Test attribute "credits_cost"
     */
    public function testPropertyCreditsCost()
    {
    }
}
